/**
 * Parallel buffers/directions
 */

#if defined (PARALLEL_BUFFER_DIMENSION_1D_X) || defined (PARALLEL_BUFFER_DIMENSION_2D_XY) || \
    defined (PARALLEL_BUFFER_DIMENSION_2D_XZ) || defined (PARALLEL_BUFFER_DIMENSION_3D_XYZ)
#define LR_BUFFER \
  FUNCTION (LEFT) \
  FUNCTION (RIGHT)
#else
#define LR_BUFFER
#endif /* PARALLEL_BUFFER_DIMENSION_1D_X || PARALLEL_BUFFER_DIMENSION_2D_XY
          PARALLEL_BUFFER_DIMENSION_2D_XZ || PARALLEL_BUFFER_DIMENSION_3D_XYZ */

#if defined (PARALLEL_BUFFER_DIMENSION_1D_Y) || defined (PARALLEL_BUFFER_DIMENSION_2D_XY) || \
    defined (PARALLEL_BUFFER_DIMENSION_2D_YZ) || defined (PARALLEL_BUFFER_DIMENSION_3D_XYZ)
#define DU_BUFFER \
  FUNCTION (DOWN) \
  FUNCTION (UP)
#else
#define DU_BUFFER
#endif /* PARALLEL_BUFFER_DIMENSION_1D_Y || PARALLEL_BUFFER_DIMENSION_2D_XY
          PARALLEL_BUFFER_DIMENSION_2D_YZ || PARALLEL_BUFFER_DIMENSION_3D_XYZ */

#if defined (PARALLEL_BUFFER_DIMENSION_1D_Z) || defined (PARALLEL_BUFFER_DIMENSION_2D_YZ) || \
    defined (PARALLEL_BUFFER_DIMENSION_2D_XZ) || defined (PARALLEL_BUFFER_DIMENSION_3D_XYZ)
#define BF_BUFFER \
  FUNCTION (BACK) \
  FUNCTION (FRONT)
#else
#define BF_BUFFER
#endif /* PARALLEL_BUFFER_DIMENSION_1D_Z || PARALLEL_BUFFER_DIMENSION_2D_YZ
          PARALLEL_BUFFER_DIMENSION_2D_XZ || PARALLEL_BUFFER_DIMENSION_3D_XYZ */

#if defined (PARALLEL_BUFFER_DIMENSION_2D_XY) || defined (PARALLEL_BUFFER_DIMENSION_3D_XYZ)
#define LRDU_BUFFER \
  FUNCTION (LEFT_DOWN) \
  FUNCTION (LEFT_UP) \
  FUNCTION (RIGHT_DOWN) \
  FUNCTION (RIGHT_UP)
#else
#define LRDU_BUFFER
#endif /* PARALLEL_BUFFER_DIMENSION_2D_XY || PARALLEL_BUFFER_DIMENSION_3D_XYZ */

#if defined (PARALLEL_BUFFER_DIMENSION_2D_YZ) || defined (PARALLEL_BUFFER_DIMENSION_3D_XYZ)
#define DUBF_BUFFER \
  FUNCTION (DOWN_BACK) \
  FUNCTION (DOWN_FRONT) \
  FUNCTION (UP_BACK) \
  FUNCTION (UP_FRONT)
#else
#define DUBF_BUFFER
#endif /* PARALLEL_BUFFER_DIMENSION_2D_YZ || PARALLEL_BUFFER_DIMENSION_3D_XYZ */

#if defined (PARALLEL_BUFFER_DIMENSION_2D_XZ) || defined (PARALLEL_BUFFER_DIMENSION_3D_XYZ)
#define LRBF_BUFFER \
  FUNCTION (LEFT_BACK) \
  FUNCTION (LEFT_FRONT) \
  FUNCTION (RIGHT_BACK) \
  FUNCTION (RIGHT_FRONT)
#else
#define LRBF_BUFFER
#endif /* PARALLEL_BUFFER_DIMENSION_2D_XZ || PARALLEL_BUFFER_DIMENSION_3D_XYZ */

#ifdef PARALLEL_BUFFER_DIMENSION_3D_XYZ
#define LRDUBF_BUFFER \
  FUNCTION (LEFT_DOWN_BACK) \
  FUNCTION (LEFT_DOWN_FRONT) \
  FUNCTION (LEFT_UP_BACK) \
  FUNCTION (LEFT_UP_FRONT) \
  FUNCTION (RIGHT_DOWN_BACK) \
  FUNCTION (RIGHT_DOWN_FRONT) \
  FUNCTION (RIGHT_UP_BACK) \
  FUNCTION (RIGHT_UP_FRONT)
#else
#define LRDUBF_BUFFER
#endif /* PARALLEL_BUFFER_DIMENSION_3D_XYZ */

#define COUNT_BUFFER \
  FUNCTION (BUFFER_COUNT)

#define PARALLEL_BUFFERS \
  LR_BUFFER \
  DU_BUFFER \
  BF_BUFFER \
  LRDU_BUFFER \
  DUBF_BUFFER \
  LRBF_BUFFER \
  LRDUBF_BUFFER \
  COUNT_BUFFER
