#ifndef FUNCTION
#define FUNCTION(X)
#endif

/**
 * Parallel buffers/directions
 */

#if defined (PARALLEL_BUFFER_DIMENSION_1D_X) || defined (PARALLEL_BUFFER_DIMENSION_2D_XY) || \
    defined (PARALLEL_BUFFER_DIMENSION_2D_XZ) || defined (PARALLEL_BUFFER_DIMENSION_3D_XYZ)
  FUNCTION(LEFT) \
  FUNCTION (RIGHT)
#endif /* PARALLEL_BUFFER_DIMENSION_1D_X || PARALLEL_BUFFER_DIMENSION_2D_XY
          PARALLEL_BUFFER_DIMENSION_2D_XZ || PARALLEL_BUFFER_DIMENSION_3D_XYZ */

#if defined (PARALLEL_BUFFER_DIMENSION_1D_Y) || defined (PARALLEL_BUFFER_DIMENSION_2D_XY) || \
    defined (PARALLEL_BUFFER_DIMENSION_2D_YZ) || defined (PARALLEL_BUFFER_DIMENSION_3D_XYZ)
  FUNCTION (DOWN) \
  FUNCTION (UP)
#endif /* PARALLEL_BUFFER_DIMENSION_1D_Y || PARALLEL_BUFFER_DIMENSION_2D_XY
          PARALLEL_BUFFER_DIMENSION_2D_YZ || PARALLEL_BUFFER_DIMENSION_3D_XYZ */

#if defined (PARALLEL_BUFFER_DIMENSION_1D_Z) || defined (PARALLEL_BUFFER_DIMENSION_2D_YZ) || \
    defined (PARALLEL_BUFFER_DIMENSION_2D_XZ) || defined (PARALLEL_BUFFER_DIMENSION_3D_XYZ)
  FUNCTION (BACK) \
  FUNCTION (FRONT)
#endif /* PARALLEL_BUFFER_DIMENSION_1D_Z || PARALLEL_BUFFER_DIMENSION_2D_YZ
          PARALLEL_BUFFER_DIMENSION_2D_XZ || PARALLEL_BUFFER_DIMENSION_3D_XYZ */

#if defined (PARALLEL_BUFFER_DIMENSION_2D_XY) || defined (PARALLEL_BUFFER_DIMENSION_3D_XYZ)
  FUNCTION (LEFT_DOWN) \
  FUNCTION (LEFT_UP) \
  FUNCTION (RIGHT_DOWN) \
  FUNCTION (RIGHT_UP)
#endif /* PARALLEL_BUFFER_DIMENSION_2D_XY || PARALLEL_BUFFER_DIMENSION_3D_XYZ */

#if defined (PARALLEL_BUFFER_DIMENSION_2D_YZ) || defined (PARALLEL_BUFFER_DIMENSION_3D_XYZ)
  FUNCTION (DOWN_BACK) \
  FUNCTION (DOWN_FRONT) \
  FUNCTION (UP_BACK) \
  FUNCTION (UP_FRONT)
#endif /* PARALLEL_BUFFER_DIMENSION_2D_YZ || PARALLEL_BUFFER_DIMENSION_3D_XYZ */

#if defined (PARALLEL_BUFFER_DIMENSION_2D_XZ) || defined (PARALLEL_BUFFER_DIMENSION_3D_XYZ)
  FUNCTION (LEFT_BACK) \
  FUNCTION (LEFT_FRONT) \
  FUNCTION (RIGHT_BACK) \
  FUNCTION (RIGHT_FRONT)
#endif /* PARALLEL_BUFFER_DIMENSION_2D_XZ || PARALLEL_BUFFER_DIMENSION_3D_XYZ */

#ifdef PARALLEL_BUFFER_DIMENSION_3D_XYZ
  FUNCTION (LEFT_DOWN_BACK) \
  FUNCTION (LEFT_DOWN_FRONT) \
  FUNCTION (LEFT_UP_BACK) \
  FUNCTION (LEFT_UP_FRONT) \
  FUNCTION (RIGHT_DOWN_BACK) \
  FUNCTION (RIGHT_DOWN_FRONT) \
  FUNCTION (RIGHT_UP_BACK) \
  FUNCTION (RIGHT_UP_FRONT)
#endif /* PARALLEL_BUFFER_DIMENSION_3D_XYZ */

  FUNCTION (BUFFER_COUNT)

#undef FUNCTION
