CALLBACK_NAME(ExBorder)
CALLBACK_NAME(ExInitial)
CALLBACK_NAME(ExExact)

CALLBACK_NAME(EyBorder)
CALLBACK_NAME(EyInitial)
CALLBACK_NAME(EyExact)

CALLBACK_NAME(EzBorder)
CALLBACK_NAME(EzInitial)
CALLBACK_NAME(EzExact)

CALLBACK_NAME(HxBorder)
CALLBACK_NAME(HxInitial)
CALLBACK_NAME(HxExact)

CALLBACK_NAME(HyBorder)
CALLBACK_NAME(HyInitial)
CALLBACK_NAME(HyExact)

CALLBACK_NAME(HzBorder)
CALLBACK_NAME(HzInitial)
CALLBACK_NAME(HzExact)

CALLBACK_NAME(Jx)
CALLBACK_NAME(Jy)
CALLBACK_NAME(Jz)
CALLBACK_NAME(Mx)
CALLBACK_NAME(My)
CALLBACK_NAME(Mz)