name: CI-test-suite

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        test_name: [t1.1, t1.2, t2.1, t2.2, t2.3, t3, t4.1, t4.2, t4.3, t5, t6.1, t6.2, t6.3, t6.4, t6.5, t6.6, t6.7, t6.8, t6.9, t6.10, t6.11, t6.12, t6.13, t7.1, t7.2, t7.3, t7.4, t7.5, t7.6, t8]
    runs-on: ubuntu-latest
    name: Test suite ${{ matrix.test_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ubuntu
        run: |
          sudo apt install openmpi-bin openmpi-common libopenmpi-dev
      - name: Build and Run
        run: |
          ./Tests/run-test.sh ${{ matrix.test_name }} 1 0 ${GITHUB_WORKSPACE}/Tests ${GITHUB_WORKSPACE}
