name: CI-test-suite-riscv64

on:
  pull_request:
    branches: [ "master" ]

  push:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  testsuite:
    if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'notest') != true) }}
    strategy:
      fail-fast: false
      matrix:
        test_name: [t1.1, t1.2, t2.1, t2.2, t2.3, t3, t4.1, t4.2, t4.3, t5, t6.1, t6.2, t6.3, t6.4, t6.5, t6.6, t6.7, t6.8, t6.9, t6.10, t6.11, t6.12, t6.13, t7.1, t7.2, t7.3, t7.4, t7.5, t7.6, t8]
    runs-on: ubuntu-latest
    name: Test suite riscv64 ubuntu 22.04 ${{ matrix.test_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ubuntu
        run: |
          sudo apt install gcc-riscv64-linux-gnu g++-riscv64-linux-gnu qemu-user-static debootstrap
      - name: Build and Run
        run: |
          export ROOTFS=${GITHUB_WORKSPACE}/rootfs/riscv64
          sudo ./create-ubuntu-rootfs.sh riscv64 jammy
          TOOLCHAIN_VER=$(ls $ROOTFS/usr/include/c++/)
          sed -i "s,set(TOOLCHAIN_VERSION \"9\"),set(TOOLCHAIN_VERSION \"$TOOLCHAIN_VER\")," riscv64-gcc-toolchain.cmake
          ./Tests/run-test.sh ${{ matrix.test_name }} 0 0 ${GITHUB_WORKSPACE}/Tests ${GITHUB_WORKSPACE} riscv64-linux-gnu-gcc riscv64-linux-gnu-g++ riscv64-gcc-toolchain.cmake
