name: CI-unit-test-arm64

on:
  pull_request:
    branches: [ "master" ]

  push:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  unit-test-matrix-relwithdebinfo-and-debug:
    if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'notest') != true) }}
    strategy:
      fail-fast: false
      matrix:
        name: [grid, dumpers-loaders, coordinate, settings, approximation, complex]
    runs-on: ubuntu-latest
    name: Unit test arm64 ubuntu 22.04 for ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ubuntu
        run: |
          sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu qemu-user-static debootstrap
      - name: Build and Run
        run: |
          export ROOTFS=${GITHUB_WORKSPACE}/rootfs/arm64
          sudo ./create-ubuntu-rootfs.sh arm64 jammy
          TOOLCHAIN_VER=$(ls $ROOTFS/usr/include/c++/)
          sed -i "s,set(TOOLCHAIN_VERSION \"7\"),set(TOOLCHAIN_VERSION \"$TOOLCHAIN_VER\")," arm64-gcc-toolchain.cmake
          ./Tools/test-units.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build "${GITHUB_WORKSPACE}/Tools/UnitTests/native/build-and-run-unit-test-${{ matrix.name }}.sh" "aarch64-linux-gnu-gcc,aarch64-linux-gnu-g++" "" "" "" "" "arm64-gcc-toolchain.cmake"

  unit-test-layout:
    if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'notest') != true) }}
    strategy:
      matrix:
        cxx11: [ON, OFF]
        complex_values: [ON, OFF]
        value_type: [f, d, ld]
    runs-on: ubuntu-latest
    name: Unit test arm64 ubuntu 22.04 for layout
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ubuntu
        run: |
          sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu qemu-user-static debootstrap
      - name: Build and Run
        run: |
          export ROOTFS=${GITHUB_WORKSPACE}/rootfs/arm64
          sudo ./create-ubuntu-rootfs.sh arm64 jammy
          TOOLCHAIN_VER=$(ls $ROOTFS/usr/include/c++/)
          sed -i "s,set(TOOLCHAIN_VERSION \"7\"),set(TOOLCHAIN_VERSION \"$TOOLCHAIN_VER\")," arm64-gcc-toolchain.cmake
          ./Tools/test-units.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build "${GITHUB_WORKSPACE}/Tools/UnitTests/native/build-and-run-unit-test-layout.sh" "aarch64-linux-gnu-gcc,aarch64-linux-gnu-g++" "RelWithDebInfo" "${{ matrix.cxx11 }}" "${{ matrix.complex_values }}" "${{ matrix.value_type }}" "arm64-gcc-toolchain.cmake"

  unit-test-internalscheme:
    if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'notest') != true) }}
    strategy:
      matrix:
        cxx11: [ON, OFF]
        complex_values: [ON, OFF]
    runs-on: ubuntu-latest
    name: Unit test arm64 ubuntu 22.04 for internalscheme
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ubuntu
        run: |
          sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu qemu-user-static debootstrap
      - name: Build and Run
        run: |
          export ROOTFS=${GITHUB_WORKSPACE}/rootfs/arm64
          sudo ./create-ubuntu-rootfs.sh arm64 jammy
          TOOLCHAIN_VER=$(ls $ROOTFS/usr/include/c++/)
          sed -i "s,set(TOOLCHAIN_VERSION \"7\"),set(TOOLCHAIN_VERSION \"$TOOLCHAIN_VER\")," arm64-gcc-toolchain.cmake
          ./Tools/test-units.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build "${GITHUB_WORKSPACE}/Tools/UnitTests/native/build-and-run-unit-test-internalscheme.sh" "aarch64-linux-gnu-gcc,aarch64-linux-gnu-g++" "RelWithDebInfo" "${{ matrix.cxx11 }}" "${{ matrix.complex_values }}" "" "arm64-gcc-toolchain.cmake"
