name: CI-unit-test-cuda

on:
  pull_request:
    branches: [ "master" ]

  push:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  unit-test-cuda-grid:
    runs-on: ubuntu-latest
    name: Unit test for cuda grid
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ubuntu
        run: |
          sudo apt-get install nvidia-cuda-toolkit
          # Check if installation is successful by running the next line
          nvcc -V
      - name: Build and Run
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/Build
          ./Tools/UnitTests/cuda/build-and-run-unit-test-cuda-grid.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build g++ gcc RelWithDebInfo ON ON 0 sm_50 0
          ./Tools/UnitTests/cuda/build-and-run-unit-test-cuda-grid.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build g++ gcc RelWithDebInfo ON OFF 0 sm_50 0

  unit-test-cuda-internalscheme:
    strategy:
      fail-fast: false
      matrix:
        complex_values: [ON, OFF]
    runs-on: ubuntu-latest
    name: Unit test for cuda internalscheme with COMPLEX_FIELD_VALUES=${{ matrix.complex_values }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ubuntu
        run: |
          sudo apt-get install nvidia-cuda-toolkit
          # Check if installation is successful by running the next line
          nvcc -V
      - name: Build and Run
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/Build
          ./Tools/UnitTests/cuda/build-and-run-unit-test-internalscheme-cuda.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build g++ gcc RelWithDebInfo ON ${{ matrix.complex_values }} 0 sm_50 0
