name: CI-unit-test

on:
  pull_request:
    branches: [ "master" ]

  push:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  unit-test-parallel-grid:
    strategy:
      fail-fast: false
      matrix:
        cxx11: [ON, OFF]
    runs-on: ubuntu-latest
    name: Unit test for parallel grid CXX11=${{ matrix.cxx11 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ubuntu
        run: |
          sudo apt install openmpi-bin openmpi-common libopenmpi-dev
      - name: Build and Run
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/Build
          ./Tools/UnitTests/mpi/build-and-run-unit-test-parallel-grid.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build g++ gcc RelWithDebInfo ${{ matrix.cxx11 }}

  unit-test-clock:
    runs-on: ubuntu-latest
    name: Unit test for clock
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ubuntu
        run: |
          sudo apt install openmpi-bin openmpi-common libopenmpi-dev
      - name: Build and Run
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/Build
          ./Tools/UnitTests/mpi/build-and-run-unit-test-clock.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build g++ gcc Debug ON
          ./Tools/UnitTests/mpi/build-and-run-unit-test-clock.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build g++ gcc Debug OFF
          ./Tools/UnitTests/mpi/build-and-run-unit-test-clock.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build g++ gcc RelWithDebInfo ON
          ./Tools/UnitTests/mpi/build-and-run-unit-test-clock.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build g++ gcc RelWithDebInfo OFF

  unit-test-matrix-relwithdebinfo-and-debug:
    strategy:
      fail-fast: false
      matrix:
        name: [grid, dumpers-loaders, coordinate, settings, approximation, complex]
    runs-on: ubuntu-latest
    name: Unit test for ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ubuntu
        run: |
          sudo apt install openmpi-bin openmpi-common libopenmpi-dev
      - name: Build and Run
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/Build
          ./Tools/UnitTests/native/build-and-run-unit-test-${{ matrix.name }}.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build g++ gcc Debug ON
          ./Tools/UnitTests/native/build-and-run-unit-test-${{ matrix.name }}.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build g++ gcc Debug OFF
          ./Tools/UnitTests/native/build-and-run-unit-test-${{ matrix.name }}.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build g++ gcc RelWithDebInfo ON
          ./Tools/UnitTests/native/build-and-run-unit-test-${{ matrix.name }}.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build g++ gcc RelWithDebInfo OFF

  unit-test-matrix-relwithdebinfo:
    strategy:
      matrix:
        name: [layout, internalscheme]
    runs-on: ubuntu-latest
    name: Unit test for ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ubuntu
        run: |
          sudo apt install openmpi-bin openmpi-common libopenmpi-dev
      - name: Build and Run
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/Build
          ./Tools/UnitTests/native/build-and-run-unit-test-${{ matrix.name }}.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build g++ gcc RelWithDebInfo ON
          ./Tools/UnitTests/native/build-and-run-unit-test-${{ matrix.name }}.sh ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/Build g++ gcc RelWithDebInfo OFF
